### PR TITLE
Small update ru_ru.json

### PR DESCRIPTION
**Pull request by Quarkrus**
Compatibility with ru-translation of Apotheosis, corrections to translation of compatibility with Tetra, and minor corrections.

### Contributor Liscence Agreement
[Full CLA](https://github.com/iron431/Irons-Spells-n-Spellbooks/blob/1.19.2/CLA.md)
*Contributors: Please "X" in the following box to acknowledge our CLA*
- [X] I have read and agree to the CLA for Iron's Spells and Spellbooks which allows me to retain my ownership in the code submitted while granting the repository owner legal rights to use my contribution.

### CODE REVIEW

**Comment by iron431** [comment]
I notice there are also a lot of changes and shortening to other words. What is the purpose of this?

**Comment by Quarkrus** [comment]
> What is the purpose of this?

It's just that we usually say "light magic", in general, my initial mistake was to call it "magic of the holy" based on the original, in Tefnya's translation it was initially adapted as light magic, the meaning of the word does not change, but it is more understandable and sounds better and is familiar to ordinary people. Sorry for such a drastic change.

**Comment by iron431** [comment]
That sounds fine, but there are also now many abbreviated words were there previously were none. Can you also explain that?

**Comment by Quarkrus** [comment]
> Can you also explain that?

This is a small compatibility fix with Tetra, because there is a character limit, and beyond the limit the word simply does not show, had to shorten some long words (just like it is done in Tetra). 
Another reason is that our words depend on the ending, and in Tetra in our language there are inconsistencies of adjectives and nouns due to different endings, so in the Tetra translation it was done so that after the dot there will be an indefinite ending that will be read differently (in feminine or masculine or indefinite) depending on the instrument without silly inconsistencies of words.

The small letters on the gems are also made specifically for compatibility with Apotheosis, since there are states of gems there and first comes the state, then the gem. It is simply not accepted for us to write almost every word with a capital letter.
With affixes, I had to choose such an ending of the word that it would fit any item regardless of masculine or feminine gender. It is my idea to change the affixes so that they would fit all items, just as it would look in English, but at the same time it would be understood and sound good (Mysterious, magical).

**Comment by iron431** [comment]
Sounds good. Thank you for the explanations

**Pull request merged**
