### PR TITLE
Cancel Spell Casts from server

### PR DESCRIPTION
**Pull request by IGN-Styly**
Adds a new method to UpdateClient class adding a way to cancel spells from the server and relay that information.

### Contributor Liscence Agreement
[Full CLA](https://github.com/iron431/Irons-Spells-n-Spellbooks/blob/1.19.2/CLA.md)
*Contributors: Please "X" in the following box to acknowledge our CLA*
- [ X] I have read and agree to the CLA for Iron's Spells and Spellbooks which allows me to retain my ownership in the code submitted while granting the repository owner legal rights to use my contribution.

### CODE REVIEW

**Comment by iron431** [comment]
[this one already exists in the api](
https://github.com/iron431/irons-spells-n-spellbooks/blob/1.19.2/src/main/java/io/redspace/ironsspellbooks/api/util/Utils.java#L381)

**Comment by IGN-Styly** [comment]
No this makes sure when the spell is cancelled the client gets updated which does not happen with the one you describe.

**Comment by iron431** [comment]
[it does update the client](https://github.com/iron431/irons-spells-n-spellbooks/blob/1.19.2/src/main/java/io/redspace/ironsspellbooks/api/spells/AbstractSpell.java#L401)

**Comment by IGN-Styly** [comment]
Then why the hell does the client keep thinking its casting when you server side cancel??????

**Comment by IGN-Styly** [comment]
and only stops when you create a state update on cast ie casting a spell.

**Comment by IGN-Styly** [comment]
LMAO my own skill issue

**Pull request closed without merging**
